name: flutter_base
description: Mr Milu's flutter base app.
publish_to: 'none'

# We use the following build number guideline: yyyy+mm+dd+incremental
version: 0.0.1+202304051

environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  browser_image_compression: 1.0.5
  cached_network_image: 3.2.3
  collection: 1.17.1
  cross_file: 0.3.3+4
  crypto: 3.0.2
  dio: 5.0.3
  easy_localization: 3.0.1
  extended_image: 7.0.2
  faker_dart: 0.1.11
  firebase_auth: 4.3.0
  firebase_core: 2.8.0
  firebase_dynamic_links: 5.0.17
  firebase_messaging: 14.3.0
  flutter:
    sdk: flutter
  flutter_config:
    git:
      url: https://github.com/ByneappLLC/flutter_config.git
  flutter_dotenv: 5.0.2
  flutter_image_compress: 1.1.3
  flutter_local_notifications: 13.0.0
  flutter_mrmilu: 1.2.0
  flutter_native_splash: 2.2.19
  flutter_riverpod: 2.3.2
  flutter_secure_storage: 8.0.0
  flutter_svg: 2.0.4
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  go_router: 6.5.1
  google_sign_in: 6.0.2
  image: 4.0.15
  image_editor: 1.3.0
  image_picker: 0.8.7+1
  injectable: 2.1.1
  json_annotation: 4.8.0
  path_provider: 2.0.14
  reactive_forms: 14.2.0
  reactive_forms_annotations: 1.0.0
  riverpod: 2.3.2
  sentry_flutter: 7.4.0
  share_plus: 6.3.1
  sign_in_with_apple: 4.3.0
  stack_trace: 1.11.0
  video_player: 2.6.0

dev_dependencies:
  build_runner: 2.3.3
  dart_code_metrics: 5.7.0
  flutter_flavorizr:
    git:
      url: https://github.com/AngeloAvv/flutter_flavorizr
      ref: master
  flutter_launcher_icons: 0.12.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  injectable_generator: 2.1.5
  integration_test:
    sdk: flutter
  json_serializable: 6.6.1
  mocktail: 0.3.0
  reactive_forms_generator: 1.0.0

dependency_overrides:
  collection: 1.17.0
  intl: 0.17.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - .env.dev
    - .env.beta
    - .env.live

  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/recoleta_medium.otf
          style: normal
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          style: normal
          weight: 500

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Flutter base (Dev)"

      android:
        applicationId: "com.flutterbasemrmilu.dev"

      ios:
        bundleId: "com.flutterbasemrmilu.dev"

    beta:
      app:
        name: "Flutter base (Beta)"

      android:
        applicationId: "com.flutterbasemrmilu.beta"
#        firebase:
#          config: ".firebase/beta/google-services.json"
        customConfig:
          signingConfig: signingConfigs.release_beta
      ios:
        bundleId: "com.flutterbasemrmilu.beta"
#        firebase:
#          config: ".firebase/beta/GoogleService-Info.plist"

    live:
      app:
        name: "Flutter base"

      android:
        applicationId: "com.flutterbasemrmilu.live"
      ios:
        bundleId: "com.flutterbasemrmilu.live"