name: flutter_base
description: Mr Milu's flutter base app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.5
  injectable: 1.5.3
  get_it: 7.2.0
  dio: 4.0.4
  riverpod: 2.0.2
  flutter_riverpod: 2.0.2
  json_annotation: 4.7.0
  freezed_annotation: 2.1.0
  firebase_core: 1.24.0
  flutter_local_notifications: 12.0.1+1
  firebase_messaging: 13.1.0
  firebase_auth: 3.11.2
  flutter_mrmilu: 0.3.0
  flutter_secure_storage: 6.0.0
  google_sign_in: 5.4.2
  sign_in_with_apple: 4.1.0
  crypto: 3.0.2
  video_player: 2.4.7
  flutter_svg: 1.1.5
  reactive_forms: 14.1.0
  flutter_dotenv: 5.0.2
  reactive_forms_annotations: 0.13.0-beta
  dio_cookie_manager: 2.0.0
  firebase_dynamic_links: 4.3.10
  cached_network_image: 3.2.2
  collection: 1.16.0
  flutter_config:
    git:
      url: https://github.com/ByneappLLC/flutter_config.git
  easy_localization: 3.0.1
  flutter_native_splash: 2.2.11
  flutter_image_compress: 1.1.3
  image_editor: 1.1.0
  extended_image: 6.3.1
  image_picker: 0.8.6
  cookie_jar: 3.0.1
  path_provider: 2.0.11
  go_router: 5.0.5
  http_parser: 4.0.2
  screenshot: 1.2.3
  share_plus: 6.2.0
  sentry_flutter: 6.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: 0.3.0
  flutter_flavorizr: 2.1.4
  flutter_lints: 2.0.1
  flutter_launcher_icons: 0.10.0
  build_runner: 2.3.0
  injectable_generator: 1.5.4
  freezed: 2.1.1
  json_serializable: 6.5.1
  reactive_forms_generator: 0.20.0-beta
  isar_generator: 3.0.2

dependency_overrides:
  analyzer: ^4.6.0
  meta: 1.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/
    - assets/translations/
    - .env.dev
    - .env.beta
    - .env.live

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/recoleta_medium.otf
          style: normal
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/poppins_medium.ttf
          style: normal
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Flutter base (Dev)"

      android:
        applicationId: "com.flutterbase-mrmilu.dev"

      ios:
        bundleId: "com.flutterbase-mrmilu.dev"

    beta:
      app:
        name: "Flutter base (Beta)"

      android:
        applicationId: "com.flutterbase-mrmilu.beta"
        firebase:
          config: ".firebase/beta/google-services.json"
        customConfig:
          signingConfig: signingConfigs.release_beta
      ios:
        bundleId: "com.flutterbase-mrmilu.beta"
        firebase:
          config: ".firebase/beta/GoogleService-Info.plist"

    live:
      app:
        name: "Flutter base"

      android:
        applicationId: "com.flutterbase-mrmilu.live"
      ios:
        bundleId: "com.flutterbase-mrmilu.live"