version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter: circleci/flutter@1.1.0

jobs:
  beta_deploy_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - install_flutter_android
      - flutter/install_android_gem
      - run: echo "$BETA_PLAY_STORE_UPLOAD_KEY" | base64 --decode > android/upload-keystore-beta.jks
      - run: echo "$BETA_PLAY_STORE_UPLOAD_KEY_PROPERTIES" | base64 --decode > android/beta.key.properties
      - run: echo "$GOOGLE_PLAY_API_KEY" | base64 --decode > android/fastlane/api-access.json
      - build_deps
      - run: cd android && bundle exec fastlane build_deploy_beta
  beta_deploy_ios:
    macos:
      xcode: 14.1.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - install_flutter_ios
      - flutter/install_ios_gem
      - build_deps
      - run: fvm flutter precache --ios
      - flutter/install_ios_pod
      - run:
          name: Fastlane
          command: cd ios && bundle exec fastlane build_deploy_beta
      - store_artifacts:
          path: output

commands:
  build_deps:
    steps:
      - run: fvm flutter pub get
      - run: fvm flutter pub run build_runner build --delete-conflicting-outputs
      - run: fvm flutter pub run easy_localization:generate -S assets/translations -f keys -O lib/ui/i18n -o locale_keys.g.dart
  install_flutter_android:
    steps:
      - run: echo 'export PATH="$CIRCLE_WORKING_DIRECTORY"/fvm:"$CIRCLE_WORKING_DIRECTORY"/.pub-cache/bin:"$CIRCLE_WORKING_DIRECTORY"/fvm/default/bin:"$PATH"' >> $BASH_ENV
      - run: echo 'export FVM_HOME="$CIRCLE_WORKING_DIRECTORY"/fvm/versions/' >> $BASH_ENV
      - run: echo 'export FVM_VERSION=2.4.1' >> $BASH_ENV
      - run: wget https://github.com/leoafarias/fvm/releases/download/"$FVM_VERSION"/fvm-"$FVM_VERSION"-linux-x64.tar.gz
      - run: tar -xf fvm-"$FVM_VERSION"-linux-x64.tar.gz
      - run: rm fvm-"$FVM_VERSION"-linux-x64.tar.gz
      - run: fvm doctor
      - run: fvm install
  install_flutter_ios:
    steps:
      - run: brew tap leoafarias/fvm
      - run: brew install fvm
      - run: fvm doctor
      - run: fvm install

workflows:
  deploy_beta:
    jobs:
      - beta_deploy_android:
          filters:
            branches:
              only: develop
      - beta_deploy_ios:
          context:
            - match
          filters:
            branches:
              only: develop
